### ISSUE TITLE
What does variable sTcp's initial value mean? How to construct?

### ISSUE THREAD

**Issue by HuangZhenyang** [Sab0tag3d/SIET#13]
Hi! I noticed that different mode has different sTcp's initial value. So I am puzzled about variable sTcp's initial value, why do you construct it like that? Could you please tell me?  

Thanks.

**Comment by Sab0tag3d** [comment]
Hi!
Cisco smart install it is a partly binary protocol with cleartext part.  We could only change this part. 
Differents payloads for differents binary functions.

**Comment by HuangZhenyang** [comment]
> Hi!
> Cisco smart install it is a partly binary protocol with cleartext part. We could only change this part.
> Differents payloads for differents binary functions.

Ok, thx! 
But, I don't understand "different binary functions", does it mean different functions like "show" or "copy" command in Cisco switch's command shell, or binary functions in the firmware?   I guess it means the latter?

**Comment by HuangZhenyang** [comment]
So that's say I want to use "show version | redirect tftp://..." command, should I rewrite the variable sTcp's initial value?
Because when I try the show command, I can't get any information from my switch.  So sad.

**Comment by Sab0tag3d** [comment]
sTcp - is a binary command to switch, you could not modify it as clear text :(
Sorry for long response
