### ISSUE TITLE
TCP-Packet

### ISSUE THREAD

**Issue by mrdos010** [Sab0tag3d/SIET#18]
Could you please explain these tow tcp packets?
many Thanks!!

sTcp = '0' * 7 + '1' + '0' * 7 + '1' + '0' * 7 + '4' + '0' * 7 + '8' + '0' * 7 + '1' + '0' * 8
000000010000000100000004000000080000000100000000

resp = '0' * 7 + '4' + '0' * 8 + '0' * 7 + '3' + '0' * 7 + '8' + '0' * 7 + '1' + '0' * 8
000000040000000000000003000000080000000100000000

**Comment by Sab0tag3d** [comment]
Hi!
I think only cisco knows what kind of data it is. From our perspective it is some binary data + IPs

**Comment by mrdos010** [comment]
i'm just wondering because based on the response you say if the device is affected or not.
and it is specifically this response :
resp = '0' * 7 + '4' + '0' * 8 + '0' * 7 + '3' + '0' * 7 + '8' + '0' * 7 + '1' + '0' * 8
000000040000000000000003000000080000000100000000

                    elif (len(data) == 24):
                        if (data.encode('hex') == resp):
                            print('[INFO]: Smart Install Client feature active on {0}'.format(ip))
                            print('[INFO]: {0} is affected'.format(ip))
                            break

**Comment by Sab0tag3d** [comment]
Yes, I think it is kind of "hello" package. We found it during experiments. 
You could also check https://svn.nmap.org/nmap/nmap-service-probes and see how nmap detect such devices. ( 
match cisco-smartinstall)

**Comment by mrdos010** [comment]
Okay. Thank You for Replay :)
