### ISSUE TITLE
I don't get the config file successfully, can you help me?

### ISSUE THREAD

**Issue by 0x0kasaku** [Sab0tag3d/SIET#5]
root@kali:~/Downloads/SIET-master# sudo python siet.py -t -g -i 192.168.1.3
sBindIp: 
-= DvK =- TFTP server 2017(p)
[INFO]: Directory already exists. OK.
[INFO]: binding socket .. ok
[INFO]: Sending TCP packet to 202.228.24.53 
[INFO]: Package send success to 202.228.24.53: 
[INFO]: Getting config done
[INFO]: All done! Waiting 60 seconds for end of connections...

**Comment by Sab0tag3d** [comment]
I see you choose two options (-t & -g) immediately. I think is better to test device and look at output before you try to get configuration file from it.

Sometimes SIET returns an empty file. I guess it connected with specific device configuration or firewall between you and device.

**Comment by 0x0kasaku** [comment]
thanks!

**Comment by ghost** [comment]
@0x0kasaku 
you need set local ip in sTFTP.py 
like this >>>for example

TftpServer('192.168.0.2', TFTP_SOCK_TIMEOUT)

**Comment by gitjc05** [comment]
> @0x0kasaku you need set local ip in sTFTP.py like this >>>for example
> 
> TftpServer('192.168.0.2', TFTP_SOCK_TIMEOUT)

Thank you so much for posting this lol, was going in circles trying to get config file until I saw this.
